sudo: required

language: c

notifications:
    email:
        - $MAIL_FOR_NOTIFICATIONS

script: make autotools && ./configure --with-open-posix-testsuite --with-realtime-testsuite && make -j$(getconf _NPROCESSORS_ONLN) && make -j$(getconf _NPROCESSORS_ONLN) install
